<?php
/**
 * Import page template.
 *
 * @var array $settings
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="wrap wcpp-importer">
	<h1><?php esc_html_e( 'Product Porter', 'wc-product-porter' ); ?></h1>
	<p class="description"><?php esc_html_e( 'Upload an export package generated by Product Porter to create or update products on this site.', 'wc-product-porter' ); ?></p>

	<form id="wcpp-import-form" enctype="multipart/form-data">
		<div class="wcpp-field-group">
			<label for="wcpp-import-file" class="wcpp-field-label"><?php esc_html_e( 'Zip Package', 'wc-product-porter' ); ?></label>
			<input type="file" id="wcpp-import-file" name="import_file" accept="application/zip" />
		</div>

		<div class="wcpp-field-group">
			<label for="wcpp-import-update" class="wcpp-field-checkbox">
				<input type="checkbox" id="wcpp-import-update" name="update_existing" value="1" />
				<?php esc_html_e( 'Update existing products when SKU matches', 'wc-product-porter' ); ?>
			</label>
		</div>

		<div class="wcpp-actions">
			<button type="submit" class="button button-primary" id="wcpp-import-start" disabled><?php esc_html_e( 'Start Import', 'wc-product-porter' ); ?></button>
			<button type="button" class="button" id="wcpp-import-cancel" style="display:none;"><?php esc_html_e( 'Cancel Import', 'wc-product-porter' ); ?></button>
		</div>
	</form>

	<div id="wcpp-import-progress" class="wcpp-progress" style="display:none;">
		<div class="wcpp-progress-bar" style="width:0%;"></div>
		<span class="wcpp-progress-text">0%</span>
	</div>

	<div id="wcpp-import-log" class="wcpp-log" style="display:none;"></div>
</div>
